services:

  book-api:
    hostname: book-api
    container_name: book-api
    image: book-api
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: gunicorn --bind :${APP_PORT} --workers 1 app.main:app --worker-class uvicorn.workers.UvicornWorker --preload --timeout 120
    env_file:
      - .env.example
    depends_on:
      - postgres


  postgres:
    image: postgres:14.4
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db:

